<?php

/**
 * BaseProfessorAreaAfinidade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $professor_id
 * @property integer $area_afinidade_id
 * @property Professor $Professor
 * @property AreaAfinidade $AreaAfinidade
 * 
 * @method integer                getProfessorId()       Returns the current record's "professor_id" value
 * @method integer                getAreaAfinidadeId()   Returns the current record's "area_afinidade_id" value
 * @method Professor              getProfessor()         Returns the current record's "Professor" value
 * @method AreaAfinidade          getAreaAfinidade()     Returns the current record's "AreaAfinidade" value
 * @method ProfessorAreaAfinidade setProfessorId()       Sets the current record's "professor_id" value
 * @method ProfessorAreaAfinidade setAreaAfinidadeId()   Sets the current record's "area_afinidade_id" value
 * @method ProfessorAreaAfinidade setProfessor()         Sets the current record's "Professor" value
 * @method ProfessorAreaAfinidade setAreaAfinidade()     Sets the current record's "AreaAfinidade" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfessorAreaAfinidade extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('professor_area_afinidade');
        $this->hasColumn('professor_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('area_afinidade_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Professor', array(
             'local' => 'professor_id',
             'foreign' => 'id'));

        $this->hasOne('AreaAfinidade', array(
             'local' => 'area_afinidade_id',
             'foreign' => 'id'));
    }
}