<?php

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $email
 * @property string $senha
 * 
 * @method string  getNome()  Returns the current record's "nome" value
 * @method string  getEmail() Returns the current record's "email" value
 * @method string  getSenha() Returns the current record's "senha" value
 * @method Usuario setNome()  Sets the current record's "nome" value
 * @method Usuario setEmail() Sets the current record's "email" value
 * @method Usuario setSenha() Sets the current record's "senha" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('nome', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('senha', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}