<?php

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $email
 * @property string $senha
 * @property string $type
 * @property string $matricula
 * @property string $endereco
 * @property string $fone_residencial
 * @property string $fone_celular
 * @property integer $curso_id
 * 
 * @method string  getNome()             Returns the current record's "nome" value
 * @method string  getEmail()            Returns the current record's "email" value
 * @method string  getSenha()            Returns the current record's "senha" value
 * @method string  getType()             Returns the current record's "type" value
 * @method string  getMatricula()        Returns the current record's "matricula" value
 * @method string  getEndereco()         Returns the current record's "endereco" value
 * @method string  getFoneResidencial()  Returns the current record's "fone_residencial" value
 * @method string  getFoneCelular()      Returns the current record's "fone_celular" value
 * @method integer getCursoId()          Returns the current record's "curso_id" value
 * @method Usuario setNome()             Sets the current record's "nome" value
 * @method Usuario setEmail()            Sets the current record's "email" value
 * @method Usuario setSenha()            Sets the current record's "senha" value
 * @method Usuario setType()             Sets the current record's "type" value
 * @method Usuario setMatricula()        Sets the current record's "matricula" value
 * @method Usuario setEndereco()         Sets the current record's "endereco" value
 * @method Usuario setFoneResidencial()  Sets the current record's "fone_residencial" value
 * @method Usuario setFoneCelular()      Sets the current record's "fone_celular" value
 * @method Usuario setCursoId()          Sets the current record's "curso_id" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('nome', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('senha', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('matricula', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('endereco', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('fone_residencial', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('fone_celular', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('curso_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');

        $this->setSubClasses(array(
             'Administrador' => 
             array(
              'type' => 'administrador',
             ),
             'Academico' => 
             array(
              'type' => 'academico',
             ),
             'Professor' => 
             array(
              'type' => 'professor',
             ),
             'Aluno' => 
             array(
              'type' => 'aluno',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}