<?php

/**
 * BaseArtigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aluno_id
 * @property clob $conteudo
 * @property enum $status
 * @property Aluno $Aluno
 * @property Doctrine_Collection $Comentarios
 * @property ArtigoAvaliacao $Avaliacao
 * 
 * @method integer             getAlunoId()     Returns the current record's "aluno_id" value
 * @method clob                getConteudo()    Returns the current record's "conteudo" value
 * @method enum                getStatus()      Returns the current record's "status" value
 * @method Aluno               getAluno()       Returns the current record's "Aluno" value
 * @method Doctrine_Collection getComentarios() Returns the current record's "Comentarios" collection
 * @method ArtigoAvaliacao     getAvaliacao()   Returns the current record's "Avaliacao" value
 * @method Artigo              setAlunoId()     Sets the current record's "aluno_id" value
 * @method Artigo              setConteudo()    Sets the current record's "conteudo" value
 * @method Artigo              setStatus()      Sets the current record's "status" value
 * @method Artigo              setAluno()       Sets the current record's "Aluno" value
 * @method Artigo              setComentarios() Sets the current record's "Comentarios" collection
 * @method Artigo              setAvaliacao()   Sets the current record's "Avaliacao" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtigo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artigo');
        $this->hasColumn('aluno_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('conteudo', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 0,
              1 => 1,
              2 => 2,
             ),
             'default' => 0,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Aluno', array(
             'local' => 'aluno_id',
             'foreign' => 'id'));

        $this->hasMany('ArtigoComentario as Comentarios', array(
             'local' => 'id',
             'foreign' => 'artigo_id'));

        $this->hasOne('ArtigoAvaliacao as Avaliacao', array(
             'local' => 'id',
             'foreign' => 'artigo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'versao',
             'className' => '%CLASS%Versao',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}