<?php

/**
 * BaseAreaAfinidade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property Doctrine_Collection $Professores
 * @property Doctrine_Collection $ProfessorAreasAfinidade
 * 
 * @method string              getNome()                    Returns the current record's "nome" value
 * @method Doctrine_Collection getProfessores()             Returns the current record's "Professores" collection
 * @method Doctrine_Collection getProfessorAreasAfinidade() Returns the current record's "ProfessorAreasAfinidade" collection
 * @method AreaAfinidade       setNome()                    Sets the current record's "nome" value
 * @method AreaAfinidade       setProfessores()             Sets the current record's "Professores" collection
 * @method AreaAfinidade       setProfessorAreasAfinidade() Sets the current record's "ProfessorAreasAfinidade" collection
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAreaAfinidade extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area_afinidade');
        $this->hasColumn('nome', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Professor as Professores', array(
             'refClass' => 'ProfessorAreaAfinidade',
             'local' => 'area_afinidade_id',
             'foreign' => 'professor_id'));

        $this->hasMany('ProfessorAreaAfinidade as ProfessorAreasAfinidade', array(
             'local' => 'id',
             'foreign' => 'area_afinidade_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nome',
             ),
             ));
        $this->actAs($sluggable0);
    }
}