<?php

/**
 * BaseArquivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $remetente_id
 * @property integer $destinatario_id
 * @property string $nome
 * @property enum $tipo
 * @property string $path
 * @property Usuario $Remetente
 * @property Usuario $Destinatario
 * 
 * @method integer getRemetenteId()     Returns the current record's "remetente_id" value
 * @method integer getDestinatarioId()  Returns the current record's "destinatario_id" value
 * @method string  getNome()            Returns the current record's "nome" value
 * @method enum    getTipo()            Returns the current record's "tipo" value
 * @method string  getPath()            Returns the current record's "path" value
 * @method Usuario getRemetente()       Returns the current record's "Remetente" value
 * @method Usuario getDestinatario()    Returns the current record's "Destinatario" value
 * @method Arquivo setRemetenteId()     Sets the current record's "remetente_id" value
 * @method Arquivo setDestinatarioId()  Sets the current record's "destinatario_id" value
 * @method Arquivo setNome()            Sets the current record's "nome" value
 * @method Arquivo setTipo()            Sets the current record's "tipo" value
 * @method Arquivo setPath()            Sets the current record's "path" value
 * @method Arquivo setRemetente()       Sets the current record's "Remetente" value
 * @method Arquivo setDestinatario()    Sets the current record's "Destinatario" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArquivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('arquivo');
        $this->hasColumn('remetente_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('destinatario_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nome', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('tipo', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'modelagem',
              1 => 'documento',
              2 => 'imagem',
              3 => 'outro',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('path', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario as Remetente', array(
             'local' => 'remetente_id',
             'foreign' => 'id'));

        $this->hasOne('Usuario as Destinatario', array(
             'local' => 'destinatario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'versao',
             'className' => '%CLASS%Versao',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}