<?php

/**
 * BaseAluno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Proposta $Proposta
 * @property Curso $Curso
 * @property Doctrine_Collection $Orientador
 * 
 * @method Proposta            getProposta()   Returns the current record's "Proposta" value
 * @method Curso               getCurso()      Returns the current record's "Curso" value
 * @method Doctrine_Collection getOrientador() Returns the current record's "Orientador" collection
 * @method Aluno               setProposta()   Sets the current record's "Proposta" value
 * @method Aluno               setCurso()      Sets the current record's "Curso" value
 * @method Aluno               setOrientador() Sets the current record's "Orientador" collection
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAluno extends Academico
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proposta', array(
             'local' => 'id',
             'foreign' => 'aluno_id'));

        $this->hasOne('Curso', array(
             'local' => 'curso_id',
             'foreign' => 'id'));

        $this->hasMany('Professor as Orientador', array(
             'refClass' => 'Orientacao',
             'local' => 'aluno_id',
             'foreign' => 'professor_id'));
    }
}