<?php

/**
 * BaseArtigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aluno_id
 * @property string $conteudo
 * @property Aluno $Aluno
 * @property Doctrine_Collection $Versoes
 * 
 * @method integer             getAlunoId()  Returns the current record's "aluno_id" value
 * @method string              getConteudo() Returns the current record's "conteudo" value
 * @method Aluno               getAluno()    Returns the current record's "Aluno" value
 * @method Doctrine_Collection getVersoes()  Returns the current record's "Versoes" collection
 * @method Artigo              setAlunoId()  Sets the current record's "aluno_id" value
 * @method Artigo              setConteudo() Sets the current record's "conteudo" value
 * @method Artigo              setAluno()    Sets the current record's "Aluno" value
 * @method Artigo              setVersoes()  Sets the current record's "Versoes" collection
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtigo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artigo');
        $this->hasColumn('aluno_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('conteudo', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Aluno', array(
             'local' => 'aluno_id',
             'foreign' => 'id'));

        $this->hasMany('ArtigoVersionamento as Versoes', array(
             'local' => 'id',
             'foreign' => 'artigo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}