<?php

/**
 * BaseProfessor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $coordenador
 * @property Doctrine_Collection $AreasAfinidade
 * @property Doctrine_Collection $ProfessorAreasAfinidade
 * @property Doctrine_Collection $AreaInteresse
 * 
 * @method boolean             getCoordenador()             Returns the current record's "coordenador" value
 * @method Doctrine_Collection getAreasAfinidade()          Returns the current record's "AreasAfinidade" collection
 * @method Doctrine_Collection getProfessorAreasAfinidade() Returns the current record's "ProfessorAreasAfinidade" collection
 * @method Doctrine_Collection getAreaInteresse()           Returns the current record's "AreaInteresse" collection
 * @method Professor           setCoordenador()             Sets the current record's "coordenador" value
 * @method Professor           setAreasAfinidade()          Sets the current record's "AreasAfinidade" collection
 * @method Professor           setProfessorAreasAfinidade() Sets the current record's "ProfessorAreasAfinidade" collection
 * @method Professor           setAreaInteresse()           Sets the current record's "AreaInteresse" collection
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfessor extends Academico
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('professor');
        $this->hasColumn('coordenador', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AreaAfinidade as AreasAfinidade', array(
             'refClass' => 'ProfessorAreaAfinidade',
             'local' => 'professor_id',
             'foreign' => 'area_afinidade_id'));

        $this->hasMany('ProfessorAreaAfinidade as ProfessorAreasAfinidade', array(
             'local' => 'id',
             'foreign' => 'professor_id'));

        $this->hasMany('AreaInteresse', array(
             'local' => 'id',
             'foreign' => 'professor_id'));
    }
}