<?php

/**
 * BaseCronograma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $proposta_id
 * @property enum $etapa
 * @property string $atividade
 * @property string $produto
 * @property date $data_entrega
 * @property string $detalhamento
 * @property Proposta $Proposta
 * 
 * @method integer    getPropostaId()   Returns the current record's "proposta_id" value
 * @method enum       getEtapa()        Returns the current record's "etapa" value
 * @method string     getAtividade()    Returns the current record's "atividade" value
 * @method string     getProduto()      Returns the current record's "produto" value
 * @method date       getDataEntrega()  Returns the current record's "data_entrega" value
 * @method string     getDetalhamento() Returns the current record's "detalhamento" value
 * @method Proposta   getProposta()     Returns the current record's "Proposta" value
 * @method Cronograma setPropostaId()   Sets the current record's "proposta_id" value
 * @method Cronograma setEtapa()        Sets the current record's "etapa" value
 * @method Cronograma setAtividade()    Sets the current record's "atividade" value
 * @method Cronograma setProduto()      Sets the current record's "produto" value
 * @method Cronograma setDataEntrega()  Sets the current record's "data_entrega" value
 * @method Cronograma setDetalhamento() Sets the current record's "detalhamento" value
 * @method Cronograma setProposta()     Sets the current record's "Proposta" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCronograma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cronograma');
        $this->hasColumn('proposta_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('etapa', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 1,
              1 => 2,
             ),
             ));
        $this->hasColumn('atividade', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('produto', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('data_entrega', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('detalhamento', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proposta', array(
             'local' => 'proposta_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}