<?php

/**
 * BaseOrientacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aluno_id
 * @property integer $professor_id
 * @property boolean $aceito
 * 
 * @method integer    getAlunoId()      Returns the current record's "aluno_id" value
 * @method integer    getProfessorId()  Returns the current record's "professor_id" value
 * @method boolean    getAceito()       Returns the current record's "aceito" value
 * @method Orientacao setAlunoId()      Sets the current record's "aluno_id" value
 * @method Orientacao setProfessorId()  Sets the current record's "professor_id" value
 * @method Orientacao setAceito()       Sets the current record's "aceito" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrientacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orientacao');
        $this->hasColumn('aluno_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('professor_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('aceito', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}