<?php

/**
 * BaseArtigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aluno_id
 * @property clob $conteudo
 * @property Aluno $Aluno
 * 
 * @method integer getAlunoId()  Returns the current record's "aluno_id" value
 * @method clob    getConteudo() Returns the current record's "conteudo" value
 * @method Aluno   getAluno()    Returns the current record's "Aluno" value
 * @method Artigo  setAlunoId()  Sets the current record's "aluno_id" value
 * @method Artigo  setConteudo() Sets the current record's "conteudo" value
 * @method Artigo  setAluno()    Sets the current record's "Aluno" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtigo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artigo');
        $this->hasColumn('aluno_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('conteudo', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Aluno', array(
             'local' => 'aluno_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'versao',
             'className' => '%CLASS%Versao',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}