<?php

/**
 * BaseConfiguracao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $instituicao
 * @property string $email
 * @property string $telefone
 * @property integer $alunos_por_professor
 * @property string $url
 * 
 * @method string       getInstituicao()          Returns the current record's "instituicao" value
 * @method string       getEmail()                Returns the current record's "email" value
 * @method string       getTelefone()             Returns the current record's "telefone" value
 * @method integer      getAlunosPorProfessor()   Returns the current record's "alunos_por_professor" value
 * @method string       getUrl()                  Returns the current record's "url" value
 * @method Configuracao setInstituicao()          Sets the current record's "instituicao" value
 * @method Configuracao setEmail()                Sets the current record's "email" value
 * @method Configuracao setTelefone()             Sets the current record's "telefone" value
 * @method Configuracao setAlunosPorProfessor()   Sets the current record's "alunos_por_professor" value
 * @method Configuracao setUrl()                  Sets the current record's "url" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfiguracao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configuracao');
        $this->hasColumn('instituicao', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('telefone', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('alunos_por_professor', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}