<?php

/**
 * BaseAreaInteresse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $professor_id
 * @property string $nome
 * @property Professor $Professor
 * 
 * @method integer       getProfessorId()  Returns the current record's "professor_id" value
 * @method string        getNome()         Returns the current record's "nome" value
 * @method Professor     getProfessor()    Returns the current record's "Professor" value
 * @method AreaInteresse setProfessorId()  Sets the current record's "professor_id" value
 * @method AreaInteresse setNome()         Sets the current record's "nome" value
 * @method AreaInteresse setProfessor()    Sets the current record's "Professor" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAreaInteresse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area_interesse');
        $this->hasColumn('professor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nome', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Professor', array(
             'local' => 'professor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}