<?php

/**
 * BaseTCC
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $etapa
 * @property integer $aluno_id
 * @property string $semestre
 * @property Aluno $Aluno
 * 
 * @method enum    getEtapa()    Returns the current record's "etapa" value
 * @method integer getAlunoId()  Returns the current record's "aluno_id" value
 * @method string  getSemestre() Returns the current record's "semestre" value
 * @method Aluno   getAluno()    Returns the current record's "Aluno" value
 * @method TCC     setEtapa()    Sets the current record's "etapa" value
 * @method TCC     setAlunoId()  Sets the current record's "aluno_id" value
 * @method TCC     setSemestre() Sets the current record's "semestre" value
 * @method TCC     setAluno()    Sets the current record's "Aluno" value
 * 
 * @package    TCCtrl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTCC extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_c_c');
        $this->hasColumn('etapa', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 0,
              1 => 1,
             ),
             ));
        $this->hasColumn('aluno_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('semestre', 'string', 6, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 6,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Aluno', array(
             'local' => 'aluno_id',
             'foreign' => 'id'));
    }
}