# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  registers_per_page : 10
  document:
    savepath: %SF_WEB_DIR%/uploads/relatorios/
  doAuth:
    signin:
      url: home/index    
  ckeditor:
    basePath:         /js/ckeditor/
    default_config: 
      jsoptions:
        bodyClass: ckeditor
        height: 320px
        language: pt-br
        resize_enabled: false
        removePlugins: elementspath
        toolbar: Basic
        toolbar_Basic: [[Bold],[Italic],[Strike],-,[NumberedList],[BulletedList]]
    article_config:
      jsoptions:
        bodyClass: ckeditor
        height: 320px
        language: pt-br
        resize_enabled: false
        removePlugins: elementspath
        toolbar: Article
        toolbar_Article: [[Cut],[Copy],[Paste],-,[Bold],[Italic],[Strike],-,[NumberedList],[BulletedList],-,[Outdent],[Indent],[Blockquote],-,[JustifyLeft],[JustifyCenter],[JustifyRight],[JustifyBlock],-,[Format]]
          