# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

home:
  url:  /home
  param: { module: home, action: index }

signin:
  url: /signin
  param: { module: login, action: signin }

signout:
  url: /signout
  param: { module: login, action: signout }

area_afinidade_action:
  url: /areaAfinidade/:id/:action
  param: { module: areaAfinidade }

proposta:
    url: /proposta
    param: { module: proposta, action: edit }

proposta_list:
    url: /propostas/:filtro
    param: { module: proposta, action: list, filtro: false }

proposta_view:
    url: /proposta/visualizar/:id
    param: { module: proposta, action: view }

proposta_action:
  url: /proposta/:id/:acao
  param: { module: proposta, action: updateStatus }

escolher_orientador:
  url: /orientacao/escolher_orientador/:aluno_id
  param: { module: orientacao, action: escolherOrientador }

sem_orientador_list:
  url: /orientacao/sem_orientador
  param: { module: orientacao, action: semOrientadorList }

orientandos_coordenador_list:
  url: /orientacao/orientandos/coordenador
  param: { module: orientacao, action: orientandosCoordenadorList }
    
orientandos_list:
  url: /orientacao/orientandos/:filtro
  param: { module: orientacao, action: orientandosList, filtro: false }
  
orientacao_action:
  url: /orientacao/orientando/:aluno_id/:professor_id/:acao
  param: { module: orientacao, action: updateStatus }  

orientador_list:
  url: /orientacao/orientadores
  param: { module: orientacao, action: orientadorList }

orientador_solicitar:
  url: /orientacao/solicitar/:professor_id
  param: { module: orientacao, action: solicitar}

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
