# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

home:
  url:  /home
  param: { module: home, action: index }

signin:
  url: /signin
  param: { module: login, action: signin }

signout:
  url: /signout
  param: { module: login, action: signout }

arquivos:
  url: /arquivos/*
  param: { module: arquivo, action: all }

forget_password:
  url: /esqueciSenha
  param: { module: login, action: forgetPassword }

relatorio:
  url: /relatorio/:tipo/*
  param: { module: relatorio, action: index }

bancas_avaliacao:
  url: /bancas/avaliacao
  param: { module: banca, action: listAvaliacao }

bancas:
  url: /bancas
  param: { module: banca, action: index }

banca_agendar:
  url: /banca/agendar
  param: { module: banca, action: new }

mensagens_enviadas:
  url: /mensagens/enviadas
  param: { module: mensagem, action: enviadas }

mensagem_responder:
  url: /mensagem/responder/:id
  param: { module: mensagem, action: reply }

mensagem_view:
  url: /mensagem/visualizar/:id
  param: { module: mensagem, action: view }

mensagens:
  url: /mensagens
  param: { module: mensagem, action: index }

artigos:
  url: /artigos
  param: { module: artigo, action: list, filtro: false }
  
artigo:
  url: /artigo
  param: { module: artigo, action: edit }

artigo_add_comment:
  url: /artigo/:artigo_id/comentario
  param: { module: artigo, action: newComment }

artigo_comentario_read:
  url: /artigo/:artigo_id/comentario/lido
  param: { module: artigo, action: markAsRead }

artigo_view_comment:
  url: /artigo/:artigo_id/comentarios
  param: { module: artigo, action: viewComments }

artigo_view:
  url: /artigo/visualizar/:id
  param: { module: artigo, action: view }

artigo_history_back:
  url: /artigo/historico/voltar/:versao
  param: { module: artigo, action: backHistory }

artigo_history:
  url: /artigo/historico
  param: { module: artigo, action: historico }

artigo_list:
  url: /artigo/:filtro
  param: { module: artigo, action: list, filtro: false }

area_afinidade_action:
  url: /areaAfinidade/:id/:action
  param: { module: areaAfinidade }

proposta:
  url: /proposta
  param: { module: proposta, action: edit }

proposta_parecer:
  url: /proposta/:id/parecer/:acao
  param: { module: proposta, action: parecer }

proposta_avaliacao:
  url: /proposta/:id/avaliacao
  param: { module: proposta, action: avaliacao }

proposta_comentario_read:
  url: /proposta/:proposta_id/comentario/:comentario_id/lido
  param: { module: proposta, action: markAsRead }

proposta_view_comment:
  url: /proposta/:proposta_id/comentarios/:local/
  param: { module: proposta, action: viewComments }

proposta_add_comment:
  url: /proposta/:proposta_id/comentario/:local/
  param: { module: proposta, action: newComment }

propostas:
  url: /propostas
  param: { module: proposta, action: list, filtro: false }

proposta_coordenador_list:
  url: /propostas/coordenador/:filtro/*
  param: { module: proposta, action: list, filtro: false, coordenador: true }

proposta_list:
  url: /propostas/:filtro/*
  param: { module: proposta, action: list, filtro: false }

proposta_avaliacao_view:
  url: /proposta/avaliacao/visualizar/:id
  param: { module: proposta, action: view, avaliacao: true }

proposta_view:
  url: /proposta/visualizar/:id
  param: { module: proposta, action: view }

proposta_action:
  url: /proposta/:id/:acao
  param: { module: proposta, action: updateStatus }

escolher_orientador:
  url: /orientacao/escolher_orientador/:aluno_id
  param: { module: orientacao, action: escolherOrientador }

sem_orientador_list:
  url: /orientacao/sem_orientador
  param: { module: orientacao, action: semOrientadorList }

orientandos_coordenador_list:
  url: /orientacao/orientandos/coordenador
  param: { module: orientacao, action: orientandosCoordenadorList }
    
orientandos_list:
  url: /orientacao/orientandos/:filtro/*
  param: { module: orientacao, action: orientandosList, filtro: false }
  
orientacao_action:
  url: /orientacao/orientando/:aluno_id/:professor_id/:acao
  param: { module: orientacao, action: updateStatus }  

orientador_list:
  url: /orientacao/orientadores
  param: { module: orientacao, action: orientadorList }

orientador_solicitar:
  url: /orientacao/solicitar/:professor_id
  param: { module: orientacao, action: solicitar}

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
