# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        TCCtrl - Sistema de Gerenciamento e Controle de TCC
    #description:  symfony project
    #keywords:     symfony, project
    language:     pt-br
    #robots:       index, follow

  stylesheets:    [screen.css, jquery-ui-1.8.5.custom.css, main.css, ie.css { condition: IE }, print.css { type: print }]

  javascripts:    [jquery-1.4.2.min.js, jquery-ui-1.8.5.custom.min.js, jquery.ui.datepicker-pt-BR.js, main.js]

  has_layout:     true
  layout:         sideMenuLayout
