<?php

/**
 * PropostaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropostaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PropostaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proposta');
    }

    public function findPropostaByProfessor($professor, $status = array(0,1,2), $execute = true) {
        $q = $this->createQuery()
           ->from('Proposta p')
           ->innerJoin('p.Aluno a')
           ->innerJoin('a.Orientacao o')
           ->where('o.professor_id = ?', $professor)
           ->andWhere('p.status IN (' . implode(',',$status) . ')');
        
        if($execute){
            return $q->execute();
        } else {
            return $q;
        }
    }

    public function findPropostaCronogramas($proposta)
    {
        $q = $this->createQuery()
           ->from('Proposta p')
           ->innerJoin('p.Cronogramas c')
           ->where('p.id = ?', $proposta)
           ->orderBy('c.etapa ASC, c.data_entrega ASC');

        return $q->fetchOne();
    }
}