<?php

/**
 * Proposta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Proposta extends BaseProposta
{
    public function getStatusDescricao()
    {
        switch($this->status){
        case 0:
            return 'Aguardando Aceitação';

            break;
        case 1:
            return 'Aceito';

            break;
        case 2:
            return 'Rejeitado';

            break;
        }
    }
}