Configuracao:
  actAs:
    Timestampable: ~
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    instituicao:
      type: string(100)
      notnull: true
    email:
      type: string(100)
      notnull: true
    telefone:
      type: string(50)
      notnull: true
    alunos_por_professor:
      type: integer
      notnull: true
    url: 
      type: string(100)
      notnull: true

Curso:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    nome:
      type: string(100)
      notnull: true
  relations:
    Professores:
      type: many
      class: Professor
      local: id
      foreign: curso_id 
    Alunos:
      type: many
      class: Aluno
      local: id
      foreign: curso_id

Usuario:
  actAs:
    Timestampable: ~
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    nome:
      type: string(50)
      notnull: true
    email:
      type: string(100)
      notnull: true
      unique: true
    senha: 
      type: string(128)
      notnull: true

Administrador:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Usuario
    #type: concrete
    type: column_aggregation
    keyField: type
    keyValue: administrador

Academico:
  #abstract: true
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Usuario
    #type: concrete
    type: column_aggregation
    keyField: type
    keyValue: academico
  columns:
    matricula: 
      type: string(20)
      notnull: true
      #unique: true
    endereco: 
      type: string(200)
      notnull: true
    fone_residencial: 
      type: string(20)
      notnull: true
    fone_celular: 
      type: string(20)
      notnull: true

Professor:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Academico
    #type: concrete
    type: column_aggregation
    keyField: type
    keyValue: professor
  columns: 
    curso_id:
      type: integer
  relations:
    AreasAfinidade:
      foreignAlias: Professores
      class: AreaAfinidade
      refClass: ProfessorAreaAfinidade
    AreasInteresse:
      type: many
      class: AreaInteresse
      local: id
      foreign: professor_id
    Orientandos:
      class: Aluno
      local: professor_id
      foreign: aluno_id      
      refClass: Orientacao
    Curso: 
      local: curso_id
      foreign: id
    ProfessorCoordenador:
      local: id
      foreign: professor_id
          
AreaAfinidade:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Sluggable:
      fields: [nome]
  columns:
    nome:
      type: string(50)
      notnull: true
  relations:
    Professor:
      foreignAlias: AreasAfinidade
      class: Professor
      refClass: ProfessorAreaAfinidade
      
ProfessorAreaAfinidade:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8    
  columns: 
    professor_id:
      type: integer(4) 
      primary: true    
    area_afinidade_id:
      type: integer(4) 
      primary: true    
  relations:
    Professor:
      foreignAlias: ProfessorAreasAfinidade
    AreaAfinidade:
      foreignAlias: ProfessorAreasAfinidade      
    
AreaInteresse:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    professor_id:
      type: integer
      notnull: true
    nome: 
      type: string(50)
      notnull: true
  relations:
    Professor:
      onDelete: CASCADE
      foreignAlias: AreasInteresse
      
Aluno:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Academico
    type: column_aggregation
    keyField: type
    keyValue: aluno
  columns: 
    curso_id:
      type: integer      
  relations:
    Proposta:
      local: id
      foreign: aluno_id
    Curso: 
      local: curso_id
      foreign: id
    Orientador:
      class: Professor
      local: aluno_id
      foreign: professor_id
      refClass: Orientacao
    Artigo:
      local: id
      foreign: artigo_id
      
Orientacao:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:      
    aluno_id:
      type: integer
      primary: true
    professor_id:
      type: integer
      primary: true
    status:
      type: enum
      values: [0, 1, 2]
      default: 0
  relations: 
    Aluno: 
      local: aluno_id
      foreign: id
    Professor: 
      local: professor_id
      foreign: id
      
Proposta:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
    Versionable:
      versionColumn: versao
      className: %CLASS%Versao
      auditLog: true
  columns:
    aluno_id:
      type: integer
      notnull: true
    titulo:
      type: string(255)
      notnull: true    
    descricao_problema:
      type: string
      notnull: true
    descricao_solucao:
      type: string
      notnull: true
    objetivos:
      type: string
      notnull: true
    status:
      type: enum
      values: [0, 1, 2]
      default: 0
  relations:
    Aluno:
      local: aluno_id
      foreign: id
    Cronogramas:
      type: many
      class: Cronograma
      local: id
      foreign: proposta_id
    Comentarios:
      type: many
      class: PropostaComentario
      local: id
      foreign: proposta_id
      
PropostaComentario:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
  columns:
    proposta_id:
      type: integer
    conteudo: 
      type: string
      notnull: true
    local: 
        type: enum
        values: [titulo, descricao_problema, descricao_solucao, objetivos]
    lido: 
      type: boolean
      default: false
      notnull: true
  relations:
    Proposta:
      local: proposta_id
      foreign: id
    
Cronograma:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
  columns:
    proposta_id:
      type: integer
    etapa:
      type: enum
      values: [1,2]
    atividade:
      type: string(255)
      notnull: true
    produto:
      type: string(100)
      notnull: true
    data_entrega:
      type: date
      notnull: true
    detalhamento:
      type: string
      notnull: false
  relations:
    Proposta:
      local: proposta_id
      foreign: id

Mensagem:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
  columns:
    remetente_id:
      type: integer
    destinatario_id:
      type: integer
    original_id:
      type: integer
    assunto:
      type: string(150)
      notnull: true
    conteudo:
      type: string
      notnull: true
    lido: 
      type: boolean
      default: false    
  relations:
    Remetente:
      class: Usuario
      local: remetente_id
      foreign: id 
    Destinatario: 
      class: Usuario
      local: destinatario_id
      foreign: id
    Original: 
      class: Mensagem
      local: original_id
      foreign: id 
    
Artigo:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
    Versionable:
      versionColumn: versao
      className: %CLASS%Versao
      auditLog: true
  columns:
    aluno_id:
      type: integer
    conteudo: 
      type: clob
      notnull: true
    status:
      type: enum
      values: [0, 1, 2]
      default: 0
  relations: 
    Aluno:
      local: aluno_id
      foreign: id
    Comentarios:
      type: many
      class: ArtigoComentario
      local: id
      foreign: artigo_id

ArtigoComentario:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
  columns:
    artigo_id:
      type: integer
    conteudo:
      type: string
      notnull: true    
    lido:
      type: boolean
      default: false
      notnull: true
  relations:
    ARtigo:
      local: artigo_id
      foreign: id