Configuracao:
  actAs:
    Timestampable: ~
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    instituicao:
      type: string(100)
      notnull: true
    email:
      type: string(100)
      notnull: true
    telefone:
      type: string(50)
      notnull: true
    alunos_por_professor:
      type: integer
      notnull: true
    url: 
      type: string(100)
      notnull: true

Curso:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    nome:
      type: string(100)
      notnull: true
  relations:
    Propostas:
      type: many
      class: Proposta
      local: id
      foreign: curso_id

Usuario:
  actAs:
    Timestampable: ~
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    nome:
      type: string(50)
      notnull: true
    email:
      type: string(100)
      notnull: true
      unique: true
    senha: 
      type: string(128)
      notnull: true

Administrador:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Usuario
    #type: concrete
    type: column_aggregation
    keyField: type
    keyValue: administrador

Academico:
  #abstract: true
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Usuario
    #type: concrete
    type: column_aggregation
    keyField: type
    keyValue: academico
  columns:
    matricula: 
      type: string(20)
      notnull: true
      #unique: true
    endereco: 
      type: string(200)
      notnull: true
    fone_residencial: 
      type: string(20)
      notnull: true
    fone_celular: 
      type: string(20)
      notnull: true

Professor:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Academico
    #type: concrete
    type: column_aggregation
    keyField: type
    keyValue: professor
  columns: 
    coordenador: 
      type: boolean
      notnull: true
      default: false
  relations:
    AreasAfinidade:
      foreignAlias: Professores
      class: AreaAfinidade
      refClass: ProfessorAreaAfinidade
    Orientandos:
      class: Aluno
      local: professor_id
      foreign: aluno_id      
      refClass: Orientacao
          
AreaAfinidade:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Sluggable:
      fields: [nome]
  columns:
    nome:
      type: string(50)
      notnull: true 
      
ProfessorAreaAfinidade:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8    
  columns: 
    professor_id:
      type: integer(4) 
      primary: true    
    area_afinidade_id:
      type: integer(4) 
      primary: true    
  relations:
    Professor:
      foreignAlias: ProfessorAreasAfinidade
    AreaAfinidade:
      foreignAlias: ProfessorAreasAfinidade      
    
AreaInteresse:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    professor_id:
      type: integer
      notnull: true
    nome: 
      type: string(50)
      notnull: true
  relations:
    Professor:
    onDelete: CASCADE
    foreignAlias: AreasInteresse
      
Aluno:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  inheritance:
    extends: Academico
    type: column_aggregation
    keyField: type
    keyValue: aluno
  relations:
    Proposta:
      local: id
      foreign: aluno_id
    Orientador:
      class: Professor
      local: aluno_id
      foreign: professor_id
      refClass: Orientacao
      
Orientacao:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  columns:      
    aluno_id:
      type: integer
      primary: true
    professor_id:
      type: integer
      primary: true
    status:
      type: enum
      values: [0, 1, 2]
      default: 0
      
Proposta:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
  columns:
    aluno_id:
      type: integer
    curso_id:
      type: integer
    titulo:
      type: string(255)
      notnull: true
    titulo:
      type: string(255)
      notnull: true
    descricao_problema:
      type: string
      notnull: true
    descricao_solucao:
      type: string
      notnull: true
    objetivos:
      type: string
      notnull: true
  relations:
    Aluno:
      local: aluno_id
      foreign: id
    Curso:
      local: curso_id
      foreign: id
    Cronogramas:
      type: many
      class: Cronogramas
      local: id
      foreign: proposta_id

Cronograma:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs:
    Timestampable: ~
  columns:
    proposta_id:
      type: integer
    etapa:
      type: enum
      values: [1,2]
    atividade:
      type: string(255)
      notnull: true
    produto:
      type: string(100)
      notnull: true
    data_entrega:
      type: date
      notnull: true
    detalhamento:
      type: string
      notnull: false
  relations:
    Proposta:
      local: proposta_id
      foreign: id